### ISSUE TITLE
The problem related to the integrity of the dependency file genepi-io-1.1.1.jar parsed by jbang

### ISSUE THREAD

**Issue by Stitch-1997** [seppinho/exome-cnv-nf#3]
Hi,

I'm currently working on detecting PSVs for each analyzed VNTR and I'm using the input algorithm provided in FastaUtil.java as suggested. However, I've encountered an issue during the process.

When running the relevant code:
`jbang export portable --verbose -O=FastaUtil.jar FastaUtil.java` , I received the following error:
```
[jbang] [0:286] jbang version 0.121.0
[jbang] [0:291] Resolving resource ref: ./FastaUtil.java
[jbang] [0:295] Resolved resource ref as: ./FastaUtil.java (cached as: /home/user/Downloads/01_Nextflow/PSV/FastaUtil.java)
[jbang] [0:335] Build required as /home/user/.jbang/cache/jars/FastaUtil.java.b6e36976b88d7d9d9938f95b191bc47a014092f3d969044c3596fdbbefe06fa9/FastaUtil.jar not readable or not found.
[jbang] [0:340] Looking for JDK: 0
[jbang] [0:344] Unable to read 'release' file in path: /home/user/.conda/envs/exome-cnv-nf
[jbang] [0:437] Using JDK: 11 (11.0.9.1-internal, current, /home/user/.conda/envs/exome-cnv-nf)
[jbang] [0:440] Resolving artifact(s): info.picocli:picocli:4.6.1, genepi:genepi-io:1.1.1
[jbang] [0:446] Repositories: jcenter=https://jcenter.bintray.com/, jfrog-genepi-maven=https://genepi.jfrog.io/artifactory/maven/
[jbang] [0:477] Resolved artifact(s) from cache: info.picocli:picocli:jar:4.6.1=/home/user/.m2/repository/info/picocli/picocli/4.6.1/picocli-4.6.1.jar, genepi:genepi-io:jar:1.1.1=/home/user/.m2/repository/genepi/genepi-io/1.1.1/genepi-io-1.1.1.jar
[jbang] [0:513] Building jar for FastaUtil.java...
[jbang] [0:514] Compile: /home/user/.conda/envs/exome-cnv-nf/bin/javac -g -classpath /home/user/.m2/repository/info/picocli/picocli/4.6.1/picocli-4.6.1.jar:/home/user/.m2/repository/genepi/genepi-io/1.1.1/genepi-io-1.1.1.jar -d /home/user/.jbang/cache/jars/FastaUtil.java.b6e36976b88d7d9d9938f95b191bc47a014092f3d969044c3596fdbbefe06fa9/classes /home/user/Downloads/01_Nextflow/PSV/FastaUtil.java
error: error reading /home/user/.m2/repository/genepi/genepi-io/1.1.1/genepi-io-1.1.1.jar; zip END header not found
[jbang] [0:710] Deleting folder /home/user/.jbang/cache/jars/FastaUtil.java.b6e36976b88d7d9d9938f95b191bc47a014092f3d969044c3596fdbbefe06fa9/classes
[jbang] [0:717] Deleting folder /home/user/.jbang/cache/jars/FastaUtil.java.b6e36976b88d7d9d9938f95b191bc47a014092f3d969044c3596fdbbefe06fa9/generated
[jbang] [0:718] [ERROR] Error during compile
dev.jbang.cli.ExitException: Error during compile
	at dev.jbang.source.buildsteps.CompileBuildStep.runCompiler(CompileBuildStep.java:149)
	at dev.jbang.source.buildsteps.CompileBuildStep.runCompiler(CompileBuildStep.java:133)
	at dev.jbang.source.buildsteps.CompileBuildStep.compile(CompileBuildStep.java:117)
	at dev.jbang.source.buildsteps.CompileBuildStep.build(CompileBuildStep.java:56)
	at dev.jbang.source.buildsteps.CompileBuildStep.build(CompileBuildStep.java:41)
	at dev.jbang.source.AppBuilder.build(AppBuilder.java:97)
	at dev.jbang.source.AppBuilder.build(AppBuilder.java:22)
	at dev.jbang.cli.BaseExportCommand.doCall(Export.java:66)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at dev.jbang.cli.JBang$3.handle(JBang.java:150)
	at dev.jbang.cli.JBang$3.handle(JBang.java:145)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at dev.jbang.Main.main(Main.java:14)
[jbang] [0:720] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
```

I've tried several methods to resolve this, such as re-downloading the genepi-io-1.1.1.jar file from the repository multiple times (using different tools like wget and curl), verifying the integrity of the downloaded file (by checking the file size and attempting to unzip it), and ensuring that my local environment settings (including Java environment variables) are correct. But unfortunately, the problem still persists.

Could you please provide some guidance on how to solve this issue? Any help would be greatly appreciated.
Thank you!

**Comment by seppinho** [comment]
Can you try again?

**Comment by Stitch-1997** [comment]
Hi, seppinho

I asked the author of jbang and the problem was solved.

The solution is to combine two steps into one: `jbang../scripts/FastaUtil.java --input "clustalO_result/aln-fasta-lpa.txt" --output "LPA-psvs.txt"`.

However, I've encountered a new problem in variation annotation now: `java genepi-annotate.jar --input variants_lpa.txt --mutation Variant --reference refs/LPA.fasta --position Pos --maplocus maplocus/MapLocusLPA.txt --columnwt wt_aas --columnmut mut_aas --output variants_lpa_annotated.txt`.

Firstly, should it be `java -jar genepi-annotate.jar` instead of `java genepi-annotate.jar`?

Secondly, your provided pipeline didn't mention how to obtain `genepi-annotate.jar`.

Could you hep me solve the problems mentioned above?
